# Generated by Django 2.2.7 on 2020-04-20 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_sale_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End of sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_use_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_abailabale_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Availabale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='currency_name',
            field=models.CharField(default='MemeCash', max_length=200, verbose_name='coin name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='shop name'),
        ),
    ]
