# Generated by Django 2.2.7 on 2020-04-20 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbabk_type',
            field=models.IntegerField(choices=[(1, 'Encourage'), (2, 'Cooporation'), (3, 'Intuition'), (4, 'Advice')], verbose_name='Type of commen'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='voice_recording',
            field=models.FileField(blank=True, max_length=5000000, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='recording'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_picture',
            field=models.ImageField(blank=True, default=None, max_length=50000, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='A picture of the result'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Achieved successfully'), (3, 'Missed'), (4, 'Aborted')], default=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very good'), (3, 'Good'), (2, "Can't tell"), (1, 'Bad idea')]),
        ),
    ]
