# Generated by Django 2.2.7 on 2020-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplay', '0002_auto_20200421_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='Israel', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_picture',
            field=models.ImageField(blank=True, default=None, max_length=500000, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='A picture of the result'),
        ),
    ]
